CREATE TABLE wga_fact (
	"Data_type" VARCHAR, 
	"Data_type_description" VARCHAR, 
	"Department_code" VARCHAR, 
	"Department_description" VARCHAR, 
	"Account_code" VARCHAR, 
	"Account_description" VARCHAR, 
	data_subtype VARCHAR, 
	data_subtype_description VARCHAR, 
	"Time" VARCHAR, 
	"Counterparty_code" VARCHAR, 
	"Couterparty_description" VARCHAR, 
	"Accounts_capital_current" VARCHAR, 
	"Budget_capital_current" VARCHAR, 
	"Resource_Capital" VARCHAR, 
	"Cash items" VARCHAR, 
	"CFER Income/Receipts" VARCHAR, 
	"CFER Resource/Capital" VARCHAR, 
	"CGA_Body_Type" VARCHAR, 
	"Dept_Group" VARCHAR, 
	"ESA" VARCHAR, 
	"Income_Category" VARCHAR, 
	"LG_Body_Type" VARCHAR, 
	"Gross/Income" VARCHAR, 
	"NAC" VARCHAR, 
	"NHS_Body_Type" VARCHAR, 
	"Non-cash items" VARCHAR, 
	"OCS" VARCHAR, 
	"PC_Body_Type" VARCHAR, 
	"PESA_Transfer" VARCHAR, 
	"SIGNAGE" VARCHAR, 
	"Cbal" VARCHAR, 
	"Local_Government_Use_only" VARCHAR, 
	"Obal" VARCHAR, 
	"Bad Debts" VARCHAR, 
	"WGA_Line" VARCHAR, 
	"WGA_Column" VARCHAR, 
	"Value" BIGINT
);
